apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack'
    receivers:
    - name: 'slack'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/'
        channel: '#dev-alerts'
        #channel: '@danfitch'
